"use client";
import { motion } from 'framer-motion';
import { Calendar, Clock, CheckCircle2, Circle } from 'lucide-react';

const PLAN = [
  { day: "Monday", goal: "Neural Networks Intro", time: "20m", done: true },
  { day: "Tuesday", goal: "Backpropagation", time: "30m", done: true },
  { day: "Wednesday", goal: "Activation Functions", time: "15m", done: false },
  { day: "Thursday", goal: "Convolutional Layers", time: "45m", done: false },
  { day: "Friday", goal: "Weekly Review & Flashcards", time: "20m", done: false },
];

export default function PlannerPage() {
  return (
    <div className="max-w-4xl mx-auto p-8 pt-12">
      <header className="mb-12">
        <h1 className="text-3xl font-semibold text-hexagon-text-primary mb-2">Study Planner</h1>
        <p className="text-hexagon-text-secondary">Your personalized learning schedule generated by AI.</p>
      </header>

      <div className="bg-hexagon-surface border border-hexagon-border rounded-2xl p-6 mb-8">
        <div className="flex items-center gap-4 mb-6">
          <div className="w-12 h-12 rounded-full bg-hexagon-accent/20 flex items-center justify-center text-hexagon-accent">
            <Calendar className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-semibold text-hexagon-text-primary">This Week</h2>
            <p className="text-hexagon-text-secondary text-sm">2 of 5 sessions completed</p>
          </div>
        </div>

        <div className="space-y-4">
          {PLAN.map((item, i) => (
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.1 }}
              key={item.day} 
              className={`flex items-center justify-between p-4 rounded-xl border ${item.done ? 'bg-hexagon-surface-hover border-hexagon-accent/20' : 'bg-background border-hexagon-border'}`}
            >
              <div className="flex items-center gap-4">
                {item.done ? <CheckCircle2 className="w-6 h-6 text-hexagon-accent" /> : <Circle className="w-6 h-6 text-hexagon-text-secondary" />}
                <div>
                  <h3 className={`font-medium ${item.done ? 'text-hexagon-text-primary line-through opacity-50' : 'text-hexagon-text-primary'}`}>{item.goal}</h3>
                  <p className="text-sm text-hexagon-text-secondary">{item.day}</p>
                </div>
              </div>
              <div className="flex items-center gap-2 text-hexagon-text-secondary">
                <Clock className="w-4 h-4" />
                <span className="text-sm font-mono">{item.time}</span>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}
